# This is a sample docker-compose file, Please follow the naming convention for the service and container name, all node
# names must begin with "Node" followed by their sequence number. For a three node cluster your service/container names
# should be Node1, Node2 and Node3 as shown below(for service names they will be lowercase). You can add additional
# parameters and configurations as required by your implementation.

version: "3.7"
services:
   node1:
      container_name: Node1
      build: Node/.
      environment:
         - NODE_NAME=node1
         - COMPANION_0=node2
         - COMPANION_1=node3
         - COMPANION_2=node4
         - COMPANION_3=node5
      volumes:
         - /persistent:/usr/src/app/Data

   node2:
      container_name: Node2
      build: Node/.
      environment:
         - NODE_NAME=node2
         - COMPANION_0=node1
         - COMPANION_1=node3
         - COMPANION_2=node4
         - COMPANION_3=node5
      volumes:
         - /persistent:/usr/src/app/Data
   node3:
      container_name: Node3
      build: Node/.
      environment:
         - NODE_NAME=node3
         - COMPANION_0=node1
         - COMPANION_1=node2
         - COMPANION_2=node4
         - COMPANION_3=node5
      volumes:
         - /persistent:/usr/src/app/Data

   node4:
      container_name: Node4
      build: Node/.
      environment:
         - NODE_NAME=node4
         - COMPANION_0=node1
         - COMPANION_1=node2
         - COMPANION_2=node3
         - COMPANION_3=node5
      volumes:
         - /persistent:/usr/src/app/Data

   node5:
      container_name: Node5
      build: Node/.
      environment:
         - NODE_NAME=node5
         - COMPANION_0=node1
         - COMPANION_1=node2
         - COMPANION_2=node3
         - COMPANION_3=node4
      volumes:
         - /persistent:/usr/src/app/Data

   #Do not change the part below
   controller:
      container_name: Controller
      build: Controller/.
      stdin_open: true
volumes:
   persistent:
