version: "3.7"
services:
  node1:
    container_name: Node1
    build: .
    ports:
      - '8080:8080'
    environment:
      - COMPANION=node2
    depends_on:
      - node2
  node2:
    container_name: Node2
    build: .
    ports:
      - '8081:8080'
    environment:
      - COMPANION=node1
